baseUrl = "/"
languageCode = "en-us"
title = "Ivan Kulagin - Freelance Backend Developer"
author = "___TOP___"
metaDataFormat = "yaml"
sectionPagesMenu = "main"
editor = ""
disableKinds = ["RSS", "sitemap"]

[taxonomies]
  tag = "tags"
  category = "categories"
  language = "languages"
  concept = "concepts"
  tool = "tools"

[params]
  author = "Ivan Kulagin"
