baseUrl = "http://vanburg.ru/"
languageCode = "en-us"
title = "Ivan Byurganovskiy personal blog"
author = "___TOP___"
metaDataFormat = "yaml"
sectionPagesMenu = "main"
editor = ""
disableKinds = ["RSS", "sitemap"]

[taxonomies]
  tag = "tags"
  category = "categories"
  language = "languages"
  concept = "concepts"
  tool = "tools"

[params]
  author = "Ivan Byurganovskiy"
